env:
    MANIFEST: https://github.com/projectarcana-aosp/manifest.git
    MANIFEST_BRANCH: 12.x
    DEVICE: raphael
    OEM: xiaomi
    DT_LINK: https://github.com/XCode219/android_device_xiaomi_raphael -b arcana-wip
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/XCode219/android_vendor_xiaomi_raphael -b twelve
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/SOVIET-ANDROID/kernel_xiaomi_raphael -b 12.0
    PLATFORM: msmnile
    KT_PATH: kernel/$OEM/$DEVICE
    HW_LINK: https://github.com/ArrowOS-Devices/android_hardware_xiaomi -b arrow-12.0
    HW_PATH: hardware/$OEM
    CM_LINK: https://gitlab.com/Panchajanya1999/azure-clang -b main
    CM_PATH: prebuilts/clang/host/linux-x86/azure-proton   
    LUNCH_COMBO: aosp_raphael-userdebug 
    TARGET: bacon
    OUTPUT: PARZ1*.zip

    # Not Recommended to Change #
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "AOSP Build"
  trigger_type: manual
  timeout_in: 120m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh
