env:
    MANIFEST: https://github.com/pa-vayu/manifest.git
    MANIFEST_BRANCH: sapphire
    DEVICE: raphael
    OEM: xiaomi
    DT_LINK: https://github.com/AzurE-007/android_device_xiaomi_raphael-2 -b sapphire
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/AzurE-007/vendor_xiaomi_raphael -b ruby
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/XCode219/android_kernel_xiaomi_raphael -b sapphire
    PLATFORM: msmnile
    KT_PATH: kernel/$OEM/$DEVICE
    VA_LINK: https://github.com/XCode219/android_vendor_aospa -b sapphire
    VA_PATH: vendor/aospa      
    LUNCH_COMBO: aospa_raphael-userdebug 
    #TARGET: xd
    OUTPUT: TEST*.zip

    # Not Recommended to Change 
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "AOSP Build"
  #trigger_type: manual
  timeout_in: 120m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh
