env:
    MANIFEST: https://github.com/PixysOS/manifest.git
    MANIFEST_BRANCH: twelve
    DEVICE: raphael
    OEM: xiaomi
    DT_LINK: https://github.com/AzureHelper/android_device_xiaomi_raphael -b pixys-12.x
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/ArrowOS-Devices/android_vendor_xiaomi_raphael -b arrow-12.1
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/LuanHalaiko/kernel_raphael_sm8150 -b raphael-unified
    PLATFORM: msmnile
    KT_PATH: kernel/$OEM/$DEVICE
    CM_LINK: https://github.com/ArrowOS-Devices/android_packages_apps_GCamGOPrebuilt -b arrow-12.1
    CM_PATH: packages/apps/GCamGOPrebuilt      
    LUNCH_COMBO: pixys_raphael-userdebug
    TARGET: pixys
    OUTPUT: TEST*.zip

    # Not Recommended to Change 
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "AOSP Build"
  #trigger_type: manual
  timeout_in: 120m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh
